name: Run Tests

'on':
  push:
    paths:
      - src/**
      - tests/**
    branches:
      - main
  pull_request:
    paths:
      - src/**
      - tests/**
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Configure Environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          echo "PYTHONPATH=src" >> $GITHUB_ENV
      - name: Test with unittest
        run: |
          python -m unittest discover -s ./tests -v